// Generated by scripts/generate-db-types.ts from supabase/migrations.
// Do not edit by hand — run `npm run db:types` after changing a migration.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      addresses: {
        Row: {
          id: string;
          user_id: string;
          label: string | null;
          full_name: string;
          phone: string;
          line1: string;
          line2: string | null;
          landmark: string | null;
          city: string;
          state: string;
          pincode: string;
          is_default: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          label?: string | null;
          full_name: string;
          phone: string;
          line1: string;
          line2?: string | null;
          landmark?: string | null;
          city: string;
          state: string;
          pincode: string;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          label?: string | null;
          full_name?: string;
          phone?: string;
          line1?: string;
          line2?: string | null;
          landmark?: string | null;
          city?: string;
          state?: string;
          pincode?: string;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "addresses_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      banners: {
        Row: {
          id: string;
          placement: string;
          title: string;
          subtitle: string;
          cta_label: string | null;
          image_path: string;
          link_url: string | null;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          placement: string;
          title?: string;
          subtitle?: string;
          cta_label?: string | null;
          image_path: string;
          link_url?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          placement?: string;
          title?: string;
          subtitle?: string;
          cta_label?: string | null;
          image_path?: string;
          link_url?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      cart_items: {
        Row: {
          id: string;
          user_id: string;
          product_id: string;
          variant_id: string | null;
          quantity: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          product_id: string;
          variant_id?: string | null;
          quantity: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          product_id?: string;
          variant_id?: string | null;
          quantity?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "cart_items_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "cart_items_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "cart_items_variant_id_fkey";
            columns: ["variant_id"];
            isOneToOne: false;
            referencedRelation: "product_variants";
            referencedColumns: ["id"];
          },
        ];
      };
      collections: {
        Row: {
          id: string;
          parent_id: string | null;
          name: string;
          slug: string;
          description: string;
          image_path: string | null;
          is_visible: boolean;
          show_in_menu: boolean;
          show_view_all: boolean;
          menu_order: number;
          menu_badge: string | null;
          is_system: boolean;
          seo_title: string | null;
          seo_description: string | null;
          created_at: string;
          updated_at: string;
          search_vector: unknown | null;
          search_text: string | null;
        };
        Insert: {
          id?: string;
          parent_id?: string | null;
          name: string;
          slug: string;
          description?: string;
          image_path?: string | null;
          is_visible?: boolean;
          show_in_menu?: boolean;
          show_view_all?: boolean;
          menu_order?: number;
          menu_badge?: string | null;
          is_system?: boolean;
          seo_title?: string | null;
          seo_description?: string | null;
          created_at?: string;
          updated_at?: string;
          search_vector?: never;
          search_text?: never;
        };
        Update: {
          id?: string;
          parent_id?: string | null;
          name?: string;
          slug?: string;
          description?: string;
          image_path?: string | null;
          is_visible?: boolean;
          show_in_menu?: boolean;
          show_view_all?: boolean;
          menu_order?: number;
          menu_badge?: string | null;
          is_system?: boolean;
          seo_title?: string | null;
          seo_description?: string | null;
          created_at?: string;
          updated_at?: string;
          search_vector?: never;
          search_text?: never;
        };
        Relationships: [
          {
            foreignKeyName: "collections_parent_id_fkey";
            columns: ["parent_id"];
            isOneToOne: false;
            referencedRelation: "collections";
            referencedColumns: ["id"];
          },
        ];
      };
      contact_submissions: {
        Row: {
          id: string;
          name: string;
          email: string;
          phone: string | null;
          subject: string | null;
          message: string;
          user_id: string | null;
          sheet_synced: boolean;
          sheet_error: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          phone?: string | null;
          subject?: string | null;
          message: string;
          user_id?: string | null;
          sheet_synced?: boolean;
          sheet_error?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          phone?: string | null;
          subject?: string | null;
          message?: string;
          user_id?: string | null;
          sheet_synced?: boolean;
          sheet_error?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "contact_submissions_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      coupons: {
        Row: {
          id: string;
          code: string;
          description: string;
          discount_type: string;
          value: number;
          min_subtotal: number;
          max_discount: number | null;
          usage_limit: number | null;
          used_count: number;
          starts_at: string | null;
          ends_at: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          description?: string;
          discount_type: string;
          value: number;
          min_subtotal?: number;
          max_discount?: number | null;
          usage_limit?: number | null;
          used_count?: number;
          starts_at?: string | null;
          ends_at?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          description?: string;
          discount_type?: string;
          value?: number;
          min_subtotal?: number;
          max_discount?: number | null;
          usage_limit?: number | null;
          used_count?: number;
          starts_at?: string | null;
          ends_at?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      menu_items: {
        Row: {
          id: string;
          menu: string;
          parent_id: string | null;
          label: string;
          collection_id: string | null;
          url: string | null;
          is_link: boolean;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          menu: string;
          parent_id?: string | null;
          label: string;
          collection_id?: string | null;
          url?: string | null;
          is_link?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          menu?: string;
          parent_id?: string | null;
          label?: string;
          collection_id?: string | null;
          url?: string | null;
          is_link?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "menu_items_collection_id_fkey";
            columns: ["collection_id"];
            isOneToOne: false;
            referencedRelation: "collections";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "menu_items_parent_id_fkey";
            columns: ["parent_id"];
            isOneToOne: false;
            referencedRelation: "menu_items";
            referencedColumns: ["id"];
          },
        ];
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          product_id: string | null;
          variant_id: string | null;
          product_name: string;
          product_slug: string | null;
          variant_label: string | null;
          sku: string | null;
          image_path: string | null;
          unit_price: number;
          quantity: number;
          line_total: number;
        };
        Insert: {
          id?: string;
          order_id: string;
          product_id?: string | null;
          variant_id?: string | null;
          product_name: string;
          product_slug?: string | null;
          variant_label?: string | null;
          sku?: string | null;
          image_path?: string | null;
          unit_price: number;
          quantity: number;
          line_total: number;
        };
        Update: {
          id?: string;
          order_id?: string;
          product_id?: string | null;
          variant_id?: string | null;
          product_name?: string;
          product_slug?: string | null;
          variant_label?: string | null;
          sku?: string | null;
          image_path?: string | null;
          unit_price?: number;
          quantity?: number;
          line_total?: number;
        };
        Relationships: [
          {
            foreignKeyName: "order_items_order_id_fkey";
            columns: ["order_id"];
            isOneToOne: false;
            referencedRelation: "orders";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "order_items_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "order_items_variant_id_fkey";
            columns: ["variant_id"];
            isOneToOne: false;
            referencedRelation: "product_variants";
            referencedColumns: ["id"];
          },
        ];
      };
      orders: {
        Row: {
          id: string;
          order_number: string;
          user_id: string | null;
          email: string;
          phone: string | null;
          status: string;
          subtotal: number;
          discount_total: number;
          shipping_total: number;
          gst_total: number;
          total: number;
          currency: string;
          coupon_id: string | null;
          coupon_code: string | null;
          shipping_address: Json;
          gift_note: string | null;
          razorpay_order_id: string | null;
          paid_at: string | null;
          shipped_at: string | null;
          delivered_at: string | null;
          cancelled_at: string | null;
          tracking_number: string | null;
          tracking_url: string | null;
          stock_issue: boolean;
          admin_note: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_number?: string;
          user_id?: string | null;
          email: string;
          phone?: string | null;
          status?: string;
          subtotal: number;
          discount_total?: number;
          shipping_total?: number;
          gst_total?: number;
          total: number;
          currency?: string;
          coupon_id?: string | null;
          coupon_code?: string | null;
          shipping_address: Json;
          gift_note?: string | null;
          razorpay_order_id?: string | null;
          paid_at?: string | null;
          shipped_at?: string | null;
          delivered_at?: string | null;
          cancelled_at?: string | null;
          tracking_number?: string | null;
          tracking_url?: string | null;
          stock_issue?: boolean;
          admin_note?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_number?: string;
          user_id?: string | null;
          email?: string;
          phone?: string | null;
          status?: string;
          subtotal?: number;
          discount_total?: number;
          shipping_total?: number;
          gst_total?: number;
          total?: number;
          currency?: string;
          coupon_id?: string | null;
          coupon_code?: string | null;
          shipping_address?: Json;
          gift_note?: string | null;
          razorpay_order_id?: string | null;
          paid_at?: string | null;
          shipped_at?: string | null;
          delivered_at?: string | null;
          cancelled_at?: string | null;
          tracking_number?: string | null;
          tracking_url?: string | null;
          stock_issue?: boolean;
          admin_note?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "orders_coupon_id_fkey";
            columns: ["coupon_id"];
            isOneToOne: false;
            referencedRelation: "coupons";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "orders_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      pages: {
        Row: {
          slug: string;
          title: string;
          body_markdown: string;
          seo_description: string | null;
          updated_at: string;
        };
        Insert: {
          slug: string;
          title: string;
          body_markdown?: string;
          seo_description?: string | null;
          updated_at?: string;
        };
        Update: {
          slug?: string;
          title?: string;
          body_markdown?: string;
          seo_description?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      payments: {
        Row: {
          id: string;
          order_id: string;
          razorpay_order_id: string;
          razorpay_payment_id: string | null;
          status: string;
          amount: number;
          method: string | null;
          error_description: string | null;
          source: string;
          raw: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          razorpay_order_id: string;
          razorpay_payment_id?: string | null;
          status: string;
          amount: number;
          method?: string | null;
          error_description?: string | null;
          source: string;
          raw?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string;
          razorpay_order_id?: string;
          razorpay_payment_id?: string | null;
          status?: string;
          amount?: number;
          method?: string | null;
          error_description?: string | null;
          source?: string;
          raw?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "payments_order_id_fkey";
            columns: ["order_id"];
            isOneToOne: false;
            referencedRelation: "orders";
            referencedColumns: ["id"];
          },
        ];
      };
      product_collections: {
        Row: {
          product_id: string;
          collection_id: string;
          sort_order: number;
        };
        Insert: {
          product_id: string;
          collection_id: string;
          sort_order?: number;
        };
        Update: {
          product_id?: string;
          collection_id?: string;
          sort_order?: number;
        };
        Relationships: [
          {
            foreignKeyName: "product_collections_collection_id_fkey";
            columns: ["collection_id"];
            isOneToOne: false;
            referencedRelation: "collections";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "product_collections_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
        ];
      };
      product_images: {
        Row: {
          id: string;
          product_id: string;
          storage_path: string;
          alt: string;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          storage_path: string;
          alt?: string;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string;
          storage_path?: string;
          alt?: string;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "product_images_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
        ];
      };
      product_variants: {
        Row: {
          id: string;
          product_id: string;
          option_name: string;
          value: string;
          swatch_hex: string | null;
          sku: string | null;
          price_override: number | null;
          stock: number;
          image_id: string | null;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          option_name?: string;
          value: string;
          swatch_hex?: string | null;
          sku?: string | null;
          price_override?: number | null;
          stock?: number;
          image_id?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string;
          option_name?: string;
          value?: string;
          swatch_hex?: string | null;
          sku?: string | null;
          price_override?: number | null;
          stock?: number;
          image_id?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "product_variants_image_id_fkey";
            columns: ["image_id"];
            isOneToOne: false;
            referencedRelation: "product_images";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "product_variants_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
        ];
      };
      products: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string;
          sku: string | null;
          tags: string[];
          price: number;
          compare_at_price: number | null;
          stock: number;
          status: string;
          whats_new_mode: string;
          badges: string[];
          rating_avg: number;
          rating_count: number;
          seo_title: string | null;
          seo_description: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
          search_vector: unknown | null;
          search_text: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string;
          sku?: string | null;
          tags?: string[];
          price: number;
          compare_at_price?: number | null;
          stock?: number;
          status?: string;
          whats_new_mode?: string;
          badges?: string[];
          rating_avg?: number;
          rating_count?: number;
          seo_title?: string | null;
          seo_description?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
          search_vector?: never;
          search_text?: never;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string;
          sku?: string | null;
          tags?: string[];
          price?: number;
          compare_at_price?: number | null;
          stock?: number;
          status?: string;
          whats_new_mode?: string;
          badges?: string[];
          rating_avg?: number;
          rating_count?: number;
          seo_title?: string | null;
          seo_description?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
          search_vector?: never;
          search_text?: never;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          email: string | null;
          full_name: string | null;
          phone: string | null;
          role: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email?: string | null;
          full_name?: string | null;
          phone?: string | null;
          role?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          full_name?: string | null;
          phone?: string | null;
          role?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      reviews: {
        Row: {
          id: string;
          product_id: string;
          user_id: string;
          rating: number;
          title: string | null;
          body: string | null;
          author_name: string;
          is_hidden: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          user_id: string;
          rating: number;
          title?: string | null;
          body?: string | null;
          author_name?: string;
          is_hidden?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string;
          user_id?: string;
          rating?: number;
          title?: string | null;
          body?: string | null;
          author_name?: string;
          is_hidden?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "reviews_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reviews_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      store_settings: {
        Row: {
          id: number;
          whats_new_days: number;
          free_shipping_threshold: number;
          shipping_fee: number;
          gst_rate: number;
          delivery_eta_text: string;
          low_stock_threshold: number;
          promo_ticker: string[];
          home_intro: string;
          home_stats: Json;
          marketplaces: Json;
          social_links: Json;
          contact_email: string | null;
          contact_phone: string | null;
          whatsapp_number: string | null;
          store_address: string | null;
          updated_at: string;
        };
        Insert: {
          id?: number;
          whats_new_days?: number;
          free_shipping_threshold?: number;
          shipping_fee?: number;
          gst_rate?: number;
          delivery_eta_text?: string;
          low_stock_threshold?: number;
          promo_ticker?: string[];
          home_intro?: string;
          home_stats?: Json;
          marketplaces?: Json;
          social_links?: Json;
          contact_email?: string | null;
          contact_phone?: string | null;
          whatsapp_number?: string | null;
          store_address?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: number;
          whats_new_days?: number;
          free_shipping_threshold?: number;
          shipping_fee?: number;
          gst_rate?: number;
          delivery_eta_text?: string;
          low_stock_threshold?: number;
          promo_ticker?: string[];
          home_intro?: string;
          home_stats?: Json;
          marketplaces?: Json;
          social_links?: Json;
          contact_email?: string | null;
          contact_phone?: string | null;
          whatsapp_number?: string | null;
          store_address?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      wishlist_items: {
        Row: {
          user_id: string;
          product_id: string;
          created_at: string;
        };
        Insert: {
          user_id: string;
          product_id: string;
          created_at?: string;
        };
        Update: {
          user_id?: string;
          product_id?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "wishlist_items_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "wishlist_items_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: {
      collection_ancestors: {
        Args: { collection_id: string };
        Returns: Json;
      };
      collection_descendant_ids: {
        Args: { root_id: string };
        Returns: string[];
      };
      generate_order_number: {
        Args: Record<PropertyKey, never>;
        Returns: string;
      };
      get_collection_products: {
        Args: {
          p_slug: string;
          p_sort?: string;
          p_min_price?: number;
          p_max_price?: number;
          p_sub_slugs?: string[];
          p_in_stock?: boolean;
          p_limit?: number;
          p_offset?: number;
        };
        Returns: Json;
      };
      get_product_cards: {
        Args: { p_ids: string[] };
        Returns: Json;
      };
      get_related_products: {
        Args: { p_product_id: string; p_limit?: number };
        Returns: Json;
      };
      in_stock: {
        Args: { p: Database["public"]["Tables"]["products"]["Row"] };
        Returns: boolean;
      };
      is_admin: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
      is_new: {
        Args: { p: Database["public"]["Tables"]["products"]["Row"] };
        Returns: boolean;
      };
      place_order_paid: {
        Args: {
          p_order_id: string;
          p_razorpay_payment_id: string;
          p_method: string;
          p_amount: number;
          p_source: string;
          p_raw?: Json;
        };
        Returns: Json;
      };
      product_card: {
        Args: { p: Database["public"]["Tables"]["products"]["Row"] };
        Returns: Json;
      };
      search_catalog: {
        Args: {
          q: string;
          p_product_limit?: number;
          p_collection_limit?: number;
        };
        Returns: Json;
      };
      search_products: {
        Args: {
          q: string;
          p_sort?: string;
          p_min_price?: number;
          p_max_price?: number;
          p_collection_slugs?: string[];
          p_in_stock?: boolean;
          p_limit?: number;
          p_offset?: number;
        };
        Returns: Json;
      };
      whats_new_days: {
        Args: Record<PropertyKey, never>;
        Returns: number;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

type PublicSchema = Database["public"];
export type Tables<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Update"];
