-- Generated by scripts/generate-seed.ts — do not edit by hand.
-- Collection tree (parents before children) and navigation menus.

insert into public.collections
  (id, parent_id, name, slug, description, show_in_menu, show_view_all, menu_order, is_system)
values
  ('8a3a495b-3440-5e99-ba7d-658276d0b01a', null, 'What''s New', 'whats-new', 'Fresh off the hook — our newest tools and handmade pieces.', true, false, 0, true),
  ('00120536-9a10-5839-be8f-5e183f6c659b', null, 'Tools', 'tools', 'Crochet hooks, knitting needles and the notions every maker needs.', true, false, 1, false),
  ('716aef5b-12cb-55a0-bd6d-ed5fc552f33e', '00120536-9a10-5839-be8f-5e183f6c659b', 'Crochet Tools', 'crochet-tools', 'Hooks for every yarn weight, from steel lace hooks to Tunisian hooks.', true, false, 0, false),
  ('cc5874f0-1064-529e-b20b-0cac6dd54743', '716aef5b-12cb-55a0-bd6d-ed5fc552f33e', 'Crochet Hooks', 'crochet-hooks', 'Ergonomic, wooden and aluminium crochet hooks in every size.', true, false, 0, false),
  ('df3c5412-8a61-5c16-9ee0-b5e2c54e3a0f', '716aef5b-12cb-55a0-bd6d-ed5fc552f33e', 'Tunisian Crochet Hooks', 'tunisian-crochet-hooks', 'Long, double-ended and interchangeable hooks for Tunisian crochet.', true, false, 1, false),
  ('fac93086-fdce-5545-bcb5-5dd808f9efc4', '00120536-9a10-5839-be8f-5e183f6c659b', 'Accessories', 'tools-accessories', 'Craft rings, project bags and handy extras for your crafting kit.', true, true, 1, false),
  ('e40e88f0-e198-557f-8db4-b58678b809db', 'fac93086-fdce-5545-bcb5-5dd808f9efc4', 'Craft Rings', 'craft-rings', 'Stainless steel rings for dreamcatchers, wreaths and macramé.', true, false, 0, false),
  ('71bf59b5-3723-5d6c-8ccb-bb151bbb1f99', 'fac93086-fdce-5545-bcb5-5dd808f9efc4', 'Project Bags', 'project-bags', 'Totes and pouches that keep your yarn and works-in-progress tidy.', true, false, 1, false),
  ('86bc3e3d-da3c-5770-b050-7d3cf6f60adf', '00120536-9a10-5839-be8f-5e183f6c659b', 'Knitting Needles', 'knitting-needles', 'Straight, circular and double-pointed knitting needles.', false, false, 2, false),
  ('7386456c-2cb6-5466-aca0-217fbff544a4', '00120536-9a10-5839-be8f-5e183f6c659b', 'Stitch Markers & Holders', 'stitch-markers-holders', 'Locking stitch markers, stitch holders and row counters.', false, false, 3, false),
  ('da58071d-7bcc-593a-bf22-b37f33b08ada', '00120536-9a10-5839-be8f-5e183f6c659b', 'Punch Needles', 'punch-needles', 'Punch needles and threaders for rug hooking and embroidery.', false, false, 4, false),
  ('5ab32a82-361b-500d-9e6a-8ac4b174f170', '00120536-9a10-5839-be8f-5e183f6c659b', 'Tatting Shuttles', 'tatting-shuttles', 'Shuttles for delicate tatted lace.', false, false, 5, false),
  ('a1d34532-61dd-586b-b6fa-2f3df74a5739', null, 'Handmade', 'handmade', 'Crochet pieces handmade by our makers, one stitch at a time.', true, false, 2, false),
  ('1c99dc36-4de1-55f3-86fd-37f7872b1bc9', 'a1d34532-61dd-586b-b6fa-2f3df74a5739', 'Home Decor', 'home-decor', 'Blankets, flowers, toys and keepsakes to make a house feel like home.', true, true, 0, false),
  ('f644131e-de9a-5e22-bcad-69222f91435a', '1c99dc36-4de1-55f3-86fd-37f7872b1bc9', 'Baby Blankets', 'baby-blankets', 'Soft chenille blankets, gentle on little ones.', true, false, 0, false),
  ('6534bdcd-b105-5176-9ad6-e9201a5b7443', '1c99dc36-4de1-55f3-86fd-37f7872b1bc9', 'Crochet Flowers', 'crochet-flowers', 'Everlasting crochet blooms — lotus, sunflowers, lilies and more.', true, false, 1, false),
  ('a60f0291-cf30-581e-9121-91b72ef05035', '1c99dc36-4de1-55f3-86fd-37f7872b1bc9', 'Key Chains', 'key-chains', 'Tiny amigurumi charms for keys, bags and backpacks.', true, false, 2, false),
  ('1eeadf9a-17d6-5e91-b2ee-a85b2f28767f', '1c99dc36-4de1-55f3-86fd-37f7872b1bc9', 'Toys', 'toys', 'Huggable amigurumi plush toys, made to be loved.', true, false, 3, false),
  ('b897c427-8bf8-52c0-b11a-5fd91a6a5357', '1c99dc36-4de1-55f3-86fd-37f7872b1bc9', 'Fridge Magnets', 'fridge-magnets', 'Cheerful crochet magnets for your fridge and boards.', false, false, 4, false),
  ('85444200-980f-542b-98a3-45260f7eb71c', '1c99dc36-4de1-55f3-86fd-37f7872b1bc9', 'Wall Hangings', 'wall-hangings', 'Crochet and macramé wall art.', false, false, 5, false),
  ('92f37b6d-a9d3-5199-8dc3-4d6ae0d046f1', 'a1d34532-61dd-586b-b6fa-2f3df74a5739', 'Accessories', 'handmade-accessories', 'Handmade bags, hair accessories and rakhis.', true, false, 1, false),
  ('8d0181b5-ea3e-5ab5-a8fe-e2be227f6df9', '92f37b6d-a9d3-5199-8dc3-4d6ae0d046f1', 'Bags', 'bags', 'Crochet bags for every day and every outing.', true, false, 0, false),
  ('699b7a13-58e7-50f4-892e-fa011953bb82', '92f37b6d-a9d3-5199-8dc3-4d6ae0d046f1', 'Hair Accessories', 'hair-accessories', 'Headbands, bandanas and scrunchies in soft yarns.', true, false, 1, false),
  ('44ddb53b-ce6a-52ef-9a89-7d529929e1ec', '92f37b6d-a9d3-5199-8dc3-4d6ae0d046f1', 'Rakhis', 'rakhis', 'Handmade crochet rakhis for Raksha Bandhan.', true, false, 2, false),
  ('4b134af0-d594-5618-b065-ab16543f8c6f', 'a1d34532-61dd-586b-b6fa-2f3df74a5739', 'Apparel', 'apparel', 'Handmade sweaters, cardigans, shawls and wraps.', false, false, 2, false),
  ('eac289bc-24d6-515e-9971-3cd4cc4a82cd', '4b134af0-d594-5618-b065-ab16543f8c6f', 'Sweaters & Cardigans', 'sweaters-cardigans', 'Cosy handmade sweaters and cardigans.', true, false, 0, false),
  ('f47d6196-a54d-5fb6-9f96-6efdd0b45c8d', '4b134af0-d594-5618-b065-ab16543f8c6f', 'Shawls & Wraps', 'shawls-wraps', 'Lightweight crochet shawls and wraps.', true, false, 1, false)
on conflict (slug) do nothing;

insert into public.menu_items
  (id, menu, parent_id, label, collection_id, url, is_link, sort_order)
values
  ('01f8110a-68ac-5cf2-983d-9ab0bb756a3c', 'header', null, 'Retail Store', null, '/retail-store', true, 100),
  ('36dfad79-0878-5e20-ae4e-a5ebe93e56a3', 'footer', null, 'Home Decor', '1c99dc36-4de1-55f3-86fd-37f7872b1bc9', null, true, 0),
  ('41235ef7-4e08-5545-9e8d-6b3441d4abe7', 'footer', '36dfad79-0878-5e20-ae4e-a5ebe93e56a3', 'Baby Blankets', 'f644131e-de9a-5e22-bcad-69222f91435a', null, true, 0),
  ('9efc8252-0eda-55cb-ab0f-8b2763b02b3e', 'footer', '36dfad79-0878-5e20-ae4e-a5ebe93e56a3', 'Crochet Flowers', '6534bdcd-b105-5176-9ad6-e9201a5b7443', null, true, 1),
  ('608a7b34-5aaf-58f8-bca9-e0b35174ad85', 'footer', '36dfad79-0878-5e20-ae4e-a5ebe93e56a3', 'Key Chains', 'a60f0291-cf30-581e-9121-91b72ef05035', null, true, 2),
  ('a9d8c23e-297f-50ee-937a-da024dff8708', 'footer', '36dfad79-0878-5e20-ae4e-a5ebe93e56a3', 'Toys', '1eeadf9a-17d6-5e91-b2ee-a85b2f28767f', null, true, 3),
  ('ba0c0338-9c4a-5b4e-a11d-4c05503ba6ca', 'footer', null, 'Accessories', '92f37b6d-a9d3-5199-8dc3-4d6ae0d046f1', null, true, 1),
  ('00242b51-81af-5c71-9a59-17f0fc558b50', 'footer', 'ba0c0338-9c4a-5b4e-a11d-4c05503ba6ca', 'Bags', '8d0181b5-ea3e-5ab5-a8fe-e2be227f6df9', null, true, 0),
  ('45dfad15-b8b1-5903-b0fc-5fe6056f2194', 'footer', 'ba0c0338-9c4a-5b4e-a11d-4c05503ba6ca', 'Hair Accessories', '699b7a13-58e7-50f4-892e-fa011953bb82', null, true, 1),
  ('0e8f6c13-cd70-5ffa-aca1-020b4af4f7e6', 'footer', 'ba0c0338-9c4a-5b4e-a11d-4c05503ba6ca', 'Rakhis', '44ddb53b-ce6a-52ef-9a89-7d529929e1ec', null, true, 2),
  ('4658fcd5-41e9-535f-9476-72cfc04c46a6', 'footer', null, 'Apparel', '4b134af0-d594-5618-b065-ab16543f8c6f', null, true, 2),
  ('e29d9bdb-ff7a-5595-a802-c4dfb4e4d975', 'footer', '4658fcd5-41e9-535f-9476-72cfc04c46a6', 'Sweaters & Cardigans', 'eac289bc-24d6-515e-9971-3cd4cc4a82cd', null, true, 0),
  ('94442761-fb76-506e-912a-83fd613afac9', 'footer', '4658fcd5-41e9-535f-9476-72cfc04c46a6', 'Shawls & Wraps', 'f47d6196-a54d-5fb6-9f96-6efdd0b45c8d', null, true, 1),
  ('692396c7-f245-50ec-8cc7-18b6caff0340', 'footer', null, 'Tools', null, null, false, 3),
  ('578672e2-5969-5a51-92d6-7601a541b6bc', 'footer', '692396c7-f245-50ec-8cc7-18b6caff0340', 'Crochet Hooks', 'cc5874f0-1064-529e-b20b-0cac6dd54743', null, true, 0),
  ('ddcebde3-8e95-5b3d-9848-0007042584d2', 'footer', '692396c7-f245-50ec-8cc7-18b6caff0340', 'Knitting Needles', '86bc3e3d-da3c-5770-b050-7d3cf6f60adf', null, true, 1),
  ('01ccb758-8b18-510c-92c0-0f5fdb7268b6', 'footer', '692396c7-f245-50ec-8cc7-18b6caff0340', 'Stitch Markers & Holders', '7386456c-2cb6-5466-aca0-217fbff544a4', null, true, 2),
  ('53e6e8ad-f281-5fb7-9cb0-59ac316ac5b6', 'footer', '692396c7-f245-50ec-8cc7-18b6caff0340', 'Project Bags', '71bf59b5-3723-5d6c-8ccb-bb151bbb1f99', null, true, 3),
  ('a21806e0-dc56-54e3-9ffc-6148f21a0274', 'footer', '692396c7-f245-50ec-8cc7-18b6caff0340', 'Punch Needles', 'da58071d-7bcc-593a-bf22-b37f33b08ada', null, true, 4),
  ('38a3fdbc-e0fe-55d5-ac56-252aeb8bd821', 'footer', '692396c7-f245-50ec-8cc7-18b6caff0340', 'Tatting Shuttles', '5ab32a82-361b-500d-9e6a-8ac4b174f170', null, true, 5),
  ('051f70bc-caa5-50df-97e5-0ec0eaf601d3', 'footer', null, 'Company', null, null, false, 4),
  ('7eab8310-6654-5434-9840-b5a59d2bea88', 'footer', '051f70bc-caa5-50df-97e5-0ec0eaf601d3', 'Our Story', null, '/our-story', true, 0),
  ('15d76658-ffb5-55e8-b63c-ed6200f2b508', 'footer', '051f70bc-caa5-50df-97e5-0ec0eaf601d3', 'Contact Us', null, '/contact', true, 1),
  ('a88fbf02-b0c4-525d-9894-22bd2fc34eb6', 'footer', '051f70bc-caa5-50df-97e5-0ec0eaf601d3', 'Retail Store', null, '/retail-store', true, 2),
  ('1a64d723-fe96-59a4-a7f7-bea66afff20c', 'footer', null, 'Support & Policies', null, null, false, 5),
  ('39711a38-830f-5980-ba20-65b637462685', 'footer', '1a64d723-fe96-59a4-a7f7-bea66afff20c', 'FAQ', null, '/faq', true, 0),
  ('645bdc4c-fcb2-5c3f-94c4-93bf3a92c9a2', 'footer', '1a64d723-fe96-59a4-a7f7-bea66afff20c', 'Privacy Policy', null, '/privacy-policy', true, 1),
  ('30a949bd-5e7a-572e-8d32-60664c2c2aff', 'footer', '1a64d723-fe96-59a4-a7f7-bea66afff20c', 'Shipping Policy', null, '/shipping-policy', true, 2),
  ('5ed651d3-83d4-5fcb-9ede-d38108cfc10a', 'footer', '1a64d723-fe96-59a4-a7f7-bea66afff20c', 'Refund Policy', null, '/refund-policy', true, 3)
on conflict (id) do nothing;
